image: openjdk:11-jdk

variables:
  ANDROID_COMPILE_SDK: "32"
  ANDROID_BUILD_TOOLS: "30.0.3"
  ANDROID_SDK_TOOLS: "4333796"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
  - unzip -d android-sdk-linux android-sdk.zip  >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - set +o pipefail
  - yes | android-sdk-linux/tools/bin/sdkmanager --licenses >/dev/null
  - set -o pipefail

stages:
  - build

assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    expose_as: APK
    name: apk
    paths:
      - app/build/outputs/apk/

lintDebug:
  stage: build
  script:
    - ./gradlew lintDebug
  artifacts:
    expose_as: Lint reports
    name: lint_reports
    paths:
      - app/build/reports/
